### ISSUE TITLE
Error running rpan-studio-26.0.2.0-linux.AppImage on Ubuntu 16.04

### ISSUE THREAD

**Issue by arosh1909** [premek/rpan#2]
Version 26 giving error on Ubuntu 16.04. While the previous version rpan-studio-25.0.7.7-linux works just fine.
![rpan error](https://user-images.githubusercontent.com/16820537/105211487-54151800-5b72-11eb-89ee-b9966688996d.png)

**Comment by premek** [comment]
Please report the issue here, this is a different repository
https://github.com/reddit/rpan-studio/issues
